### ISSUE TITLE
Problems loading file

### ISSUE THREAD

**Issue by EdwardRosenfeld** [Rcomian/rcomian.github.com#1]
I had quite an issue with Avast anti-virus. The program was sure that your file for windows was a dangerous virus.

**Comment by Rcomian** [comment]
oh man, let me scan those and make sure they're ok.

**Comment by Rcomian** [comment]
Ok, I *think* it's a false alarm. It's definitely the file I uploaded - I've checked the sha256sum.
VirusTotal online scan has 3 hits, but two are just saying it's compressed and a third seems unlikely - I have no evidence of that virus on my machine. All the other main engines come back with nothing.

Might be worth double checking the file you've got at: https://www.virustotal.com
If you upload it, the sha256 should be d2f5d4d0baf0ef50eb1ae5e8d0689a09907c98ee4ab48724bb18fae9d1dea159

**Comment by Rcomian** [comment]
Also the machine I build on is a rarely used vm. I use it for steam games, gog games and building rack things

**Comment by EdwardRosenfeld** [comment]
I heard from Avast and they gave the ok on the file, as you said, an error...no sweat...al  OK...


Thanks, Eddie 

    On Thursday, September 20, 2018, 3:54:21 PM EDT, Jim T <notifications@github.com> wrote:  
 
 
Also the machine I build on is a rarely used vm. I use it for steam games, gog games and building rack things

**Comment by Rcomian** [comment]
that's cool, glad it was just a false positive.
